# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_manipulator_controller:
  ros__parameters:
    joints:
      - shoulder_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity